### ISSUE TITLE
Broken on 1.77.1

### ISSUE THREAD

**Issue by jshbrntt** [blackmann/fonted#1]
```
Version: 1.77.1 (user setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

This is the error I get when running `Fonted: Enable`.

```
A system error occurred (ENOENT: no such file or directory, open '/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/code/electron-sandbox/workbench/workbench.html'): Error: A system error occurred (ENOENT: no such file or directory, open '/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/code/electron-sandbox/workbench/workbench.html')
	at m.h (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:99:126151)
	at m.$executeContributedCommand (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:99:126701)
	at c.N (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:109:11655)
	at c.M (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:109:11373)
	at c.H (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:109:10454)
	at c.G (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:109:9432)
	at /home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:109:8220
	at E.invoke (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:14916)
	at /home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:125:16654
	at E.invoke (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:14916)
	at s.E (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:18982)
	at /home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:16970
	at E.invoke (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at d.acceptChunk (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:12647)
	at /home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:11934
	at E.invoke (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at n.u (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:28919)
	at n.acceptFrame (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:28725)
	at E.l (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:27312)
	at /home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:24635
	at Socket.s (/home/jshbrntt/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/out/vs/workbench/api/node/extensionHostProcess.js:72:22469)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

You need to force the extension to run as a local host extension, as it will break when running on a remote host such as WSL.

I had to add the following to my `settings.json` file to force it to run on the local host rather than WSL.

```
"remote.extensionKind": {
    "degreat.fonted": [
        "ui"
    ]
},
```

**Comment by blackmann** [comment]
Hi @jshbrntt ,

I've updated the extension to have this settings by default, can you remove your manual override and check if it works.
